---
- hosts: jenkins
  user: root

  tasks:
  - name: install java
    yum:
      name: java
      state: present

  - name: download jenkins.repo
    get_url:
     url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
     dest: /etc/yum.repos.d/jenkins.repo

  - name: import jenkins key
    rpm_key:
     state: present
     key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: install jenkins
    yum:
      name: jenkins
      state: latest

  - name: start jenkins
    service:
      name: jenkins
      state: started
 
  - name: pkgs necessarios
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - lvm2
      - yum-utils
      - device-mapper-persistent-data

  - name: repositorio docker
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    become: yes

  - name: habilitando repo
    ini_file:
      dest: /etc/yum.repos.d/docker-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: 0
    become: yes

  - name: docker
    yum:
      name: docker
      state: latest

  - name: iniciar servico docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: liberando firewall jenkins
    shell: firewall-cmd --permanent --zone=public --add-port=8080/tcp

  - name: reboot firewall
    shell: firewall-cmd --reload
